const text = `Public blockchains present a paradox of ownership. No-one controls them and anyone can use them, given a connection and an ability to speak the common tongue. The network is ownerless, yet anyone who creates a key ‘owns’ any coins associated with it, so everyone is an owner. This confusion reveals how ‘ownership’ is shifting and highlights the opportunity we have not to implement an ‘ownership economy’, but to reimagine what being an owner means.
We can begin this process by asking, “What do I actually control?”
In Bitcoin, I can sign over an unspent transaction output to another address. In Ethereum and other account-based models, I can sign a message which changes a value stored in shared state. In each case, I am not the sole possessor or controller, I am a signatory on an event shared with everyone who participates in the network.
So, ownership in digital economies is really about the meaningful signatures required to execute state changes while maintaining consensus. Is ownership shifting from an ability to demonstrate control or possession to the ability to make collective meaning? If so, the change in signification is a radical one, because ownership is traditionally about exclusive rights, whereas meaning is made valuable by how widely it is shared. The medium may be massaging ownership to mean its opposite: “content can now beproliferated instead of protected”. We may, for the first time online, design primarily for multiple, simultaneous use, rather than individual consumption.
The very first proto-NFTs hinted at this shift. “Towards An Ownership Layer for the Internet” speaks about ways to “make ownership actions of digital property universally accessible.” Only in web3 can the words ‘ownership’ and ‘universally accessible’ be found together sensibly. Indeed, the first work about ownership and art in Ethereum ends by pointing out that this network differs from traditional art markets because it is public, transparent, and voluntary.
The Plural Good
How does making a sign differ from exerting control or claiming possession? Once claimed, possessed or controlled, the story is forced to a close, which is why the ‘ownership economy’ is singular. Someone wins and everyone else loses. However, your signature is at once totally unique—there is only one in the whole world—and yet it can be made many times over without losing meaning. So it is that we can talk of Signature Economies in the plural, while still remembering that such plurality is made meaningfully valuable by individual speech acts within and across a shared, public ledger. To quote Wendell Berry, “Perhaps our most serious cultural loss in recent centuries is the knowledge that some things, though limited, are inexhaustible.”
As the meaning of ‘ownership’ shifts, it drags other critical terms along with it, like ‘social security’. This has a cascading effect, such that words like ‘welfare’ may come to mean more than just financial stability secured by bureaucratic states, signifying—in addition to the financial—our access to and participation in “authentic communication channels” through which we establish, by consensus, shared and open state. In this context, and keeping in mind our responsibility not just for our own keys but the recovery of others, “Make meaningful economies” is a more crafty cultural signal than “Own your piece of the economy”.
While our state is globally shared, it is critical that we design economies, plural. Our work must not be about replicating one dominant economic paradigm, supposedly better than the last. It could instead be about cultivating the space for many different concepts of value to interface with one another in creative ways which don’t aim for cancerous growth, but are self-sustaining, resilient, and responsible.
Response-ability
Perhaps this work is not about the right to control, but about cultivating responsibility? Having no intermediaries creates certain benefits, but it is—as always—a tradeoff: if you misplace your mnemonic, it means no more magic internet money and there is no customer service to help you. However, this can be addressed by interdependent architectures and “by embedding security in sociality [such that we] can always regenerate keys through community recovery”.
The phrase ‘not your keys, not your coins’ is often used to connote sovereign rights. If you hold the keys, then you have an absolute and unimpeachable right to sign as you please. It turns out, though, that managing your own keys is risky and hard. The user experience of this is bad not because we lack great designers, but because responsibility is an inherently difficult feature for which to design. This is because response-ability is not about discrete, individual actions which release the most dopamine, but our unique relationships within a network.
Single sign-ons represent us as separate users and when—neatly categorized—we log in, we also hand over authority, become the audience, and are subject to someone else’s story. However, signed messages which change the state of a network no-one controls require recurring participation as we commit individual transactions into a shared, relatable context. The gift of being able to express what value means to you is always already bound to the responsibility you have to be aware of what you are saying and how you are speaking it into the world.
Moreover, the ability to bear responsibility is a prerequisite for meaningful legal rights, a point made explicit in signature economies. Just as there is no meaningful speech on-chain without cost, any rights you may enjoy on-chain are simultaneous with the responsibility you bear for the keys used to sign for them. Used intentionally, digital bearer instruments could be about more than claims or access, extending to the “right to care” and the “freedom to exercise responsibility”. This kind of careful responsibility signifies the same internal state as words like kaitiaki: guardianship that is about relationship, not control; about response-ability to, not responsibility for.
Can we create a culture where I am wealthy by virtue of what I care for, rather than what I control? Where wealth means “ having enough to share” because who you are is already enough. Can we create environments where what I hold is made valuable because of the community to which it binds me? This is what good mechanism design crafts: incentive structures which create the context required for people to sign a communal record of the things they care for most as individuals. The intercourse of personal meaning and collective memory is the root of lasting value.
Re-iterate
All of which brings us to the word ‘signature’. It connotes both that which is irreducibly and uniquely you - your signature dish, signature tune, signature shot - and that which binds you contractually to a world beyond yourself. In Derrida’s words, it is at once singular and iterable. Two wonderful phrases that carry the same kind of paradoxical structure are the isiZulu saying, “umuntu ngumuntu ngabantu”: a human being is only a human being through other human beings, and the Kanien'kehá:ka phrase “I’ionrhek thiia’tionha’ak nonen tion’kwatorohon”: we are individual but we discover ourselves within the collective. Both sayings hold the possibility and promise of individuation: you can become a full human being; but you can only do so in community. You can only do so through fulfilling your responsibilities in relationship, not through asserting your rights.
The word ‘economies’ contains this same double-directedness. It comes from the Greek oikos, which means ‘house’. Sustainable household management requires micro insights into each of our habits, as well as macro perspectives of our shared habitations, including the planet which houses us all. Home is an irreducible, internal feeling that simultaneously requires relationship and familiarity with others.
Similarly, meaningful words arise due to individual creativity within a community who agrees upon their use, which is why language itself is the only logically decentralized system we know. When what we say and how we say it invites people in and calls up a response, meaning is made more widely accessible. When we cast these new networks as economies of sign rather than of ownership, then the game becomes one of actively finding more people able to respond, rather than extracting rent from my exclusive right to some artificially scarce series of bits.
Economies of sign emerge from the shared experience of public consensus rules, clearly priced opcodes, and executable speech. The value of such economies is held in positively signed individual messages which enact meaning within the context of a collective record that no-one controls. This doesn’t mean we can now name (or code) the dao; it just means we can iteratively sign into existence the kinds of shared state which will allow individuals to experience harmoniously what words like dao signify in their personal contexts.
How can I take responsibility without the resources to make my signature meaningful, though? I have tried to use words to speak my imagination into existence, and have seen the limits of such work. My signatures do not move markets. However, markets are not the arbiters of meaning, they are mechanisms for efficient resource allocation. Your signature is not made meaningful by its effects: your signature is meaningful by virtue of its singular existence. New forms of ignorance and injustice will always appear, yet knowing this and still having the will and creativity to iterate over incentive structures is what will continually imbue our shared record with true beauty.
“Everything depends on the individual human being, regardless of how small a number of like-minded people there are […] on each person […] creatively making the meaning of life a reality in his or her own being.”
- Viktor Frankl
Song of Signs
The ‘coin’ your key controls comes from the Latin word ‘cuneus’, which once meant ‘cornerstone’. In this single sign is the signal we can use to understand the shifting meaning of ownership. Will your coins be the cornerstones of pluriverses, or the currency of one more unjust and unequal realm?
Because it has worked almost exactly as it should, one of the few things people notice about the Ethereum Foundation is the principle of subtraction. Do not make yourself the onlyOwner: it is by subtracting from your own importance that care for, and improvement of, our communal capacity and capability can happen.
Seek to improve the people around you by humbling yourself and handing over power at every chance, without shirking responsibility. Delighted, you will gradually find yourself doing nothing, being happy.
There is also another connotation waiting for us in the word ‘economy’: to use sparingly. The messages we sign as a means of maintaining our shared record cannot be censored by anyone, but they can be seen by everyone, so be careful what kinds of money you make meaningful. With programmable power comes permanent accountability. To better understand the deeper meaning of 'power', though, we once again turn to the poets:
“Real power has nothing to do with force, control, status, or money. Real power is the persistent courage to be at ease with the unsolved and the unfinished. To be able to recognise, in the scattered graffiti of your desires, the signature of the eternal.”
- John O'Donohue
‘The Ownership Economy’ doesn’t describe the kind of world we want to create together. Noticing this is not just a question about what kind of web we want; it’s about how we see ourselves. Do we trust ourselves enough to signal the kinds of economies we wish to engage in, and do we have the courage to sign the sorts of transactions which will bring that about?
The word ‘token’ comes from a Germanic root meaning ‘to teach’. Kei Kreutler teaches that it also carries a trace of the older word sunthemata: divine symbols within all existence meant to assist the soul on its journey from, and back to, grace. When we leave a token of love or appreciation for no reason other than the simple recognition that love and gratitude are already their own reward, then such signed symbols can guide us all home, across time. This is what I understand courageous signatures to mean: not just the set which shifts markets and remakes the world, but the superset which marks what I already mean, which re-members this singular human response to our shared being.`

export default text